# Generated by Django 4.2.16 on 2024-11-21 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_remove_category_task'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='task',
            field=models.ManyToManyField(to='category.category'),
        ),
    ]
